name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: fabric
          path: |
            fabric/build/libs/*.jar
            !fabric/build/libs/*-dev-shadow.jar
            !fabric/build/libs/*-sources.jar
      - uses: actions/upload-artifact@v4
        with:
          name: neoforge
          path: |
            neoforge/build/libs/*.jar
            !neoforge/build/libs/*-dev-shadow.jar
            !neoforge/build/libs/*-sources.jar
