deps.fabric_loader={{fabric_loader_version}}
deps.fabric_api={{fabric_api_version}}
deps.neoforge={{neoforge_version}}
deps.mc_dep_fabric={{mc_dep_fabric}}
deps.mc_dep_neoforge={{mc_dep_neoforge}}
deps.neoforge_dep={{neoforge_dep}}
