use crate::config::{McmodConfig, VersionTarget, Versions};
use crate::error::Result;
use crate::template::{self, render, strip_conditional_blocks};
use crate::util::{write_binary, write_file};
use crate::version_meta;
use colored::Colorize;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// Default server.properties for dev use.
/// online-mode and enforce-secure-profile are disabled so unauthenticated dev clients can connect.
const SERVER_PROPERTIES: &str = "\
#Minecraft server properties - generated by mcmod init
accepts-transfers=false
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
difficulty=easy
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=creative
generate-structures=false
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\\:normal
log-ips=true
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=60000
max-world-size=29999984
motd=A Minecraft Server
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=60
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=10
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=10
white-list=false
";

pub struct InitOptions {
    pub dir: PathBuf,
    pub mod_id: Option<String>,
    pub mod_name: Option<String>,
    pub package: Option<String>,
    pub author: Option<String>,
    pub description: Option<String>,
    pub language: Option<String>,
    pub loaders: Vec<String>,
    pub minecraft_versions: Vec<String>,
    pub ci: Option<bool>,
    pub server: Option<bool>,
    pub publishing: Option<bool>,
    pub modrinth_id: Option<String>,
    pub curseforge_id: Option<String>,
    pub testing: Option<bool>,
    pub offline: bool,
    pub force: bool,
}

pub fn run(opts: InitOptions) -> Result<()> {
    println!("{}", "\n  mcmod init\n".bold().cyan());

    // Warn if target directory is non-empty
    if opts.dir.exists() && !opts.force {
        let has_files = std::fs::read_dir(&opts.dir)
            .map(|mut d| d.next().is_some())
            .unwrap_or(false);
        if has_files {
            println!(
                "{}",
                format!(
                    "  Warning: {} is not empty. Files may be overwritten.",
                    opts.dir.display()
                )
                .yellow()
            );
            let proceed = prompt_confirm("  Continue?", false)?;
            if !proceed {
                return Err(crate::error::McmodError::Other(
                    "Aborted — directory is not empty (use --force to skip this check)".to_string(),
                ));
            }
        }
    }

    let interactive = opts.mod_id.is_none();

    // Load global config for defaults (never blocks init)
    let global = crate::global_config::GlobalConfig::load().unwrap_or_default();

    // Derive default mod ID from directory name
    let default_mod_id = slugify_dir_name(&opts.dir);

    // Gather inputs
    let mod_id = if let Some(id) = opts.mod_id {
        id
    } else {
        prompt_input("Mod ID", &default_mod_id)?
    };
    crate::util::validate_mod_id(&mod_id)?;

    let mod_name = if let Some(name) = opts.mod_name {
        name
    } else {
        let default = default_mod_name(&mod_id);
        prompt_input("Mod Name", &default)?
    };

    let author = if let Some(a) = opts.author {
        a
    } else {
        let default_author = global.defaults.author.as_deref().unwrap_or("Your Name");
        prompt_input("Author", default_author)?
    };

    let package = if let Some(pkg) = opts.package {
        pkg
    } else {
        let author_slug = slugify_for_package(&author);
        let default = format!("com.{author_slug}.{mod_id}");
        prompt_input("Package", &default)?
    };
    crate::util::validate_package(&package)?;

    let description = if let Some(d) = opts.description {
        d
    } else {
        prompt_input("Description", "A Minecraft mod")?
    };

    let language = if let Some(l) = opts.language {
        l
    } else if interactive {
        let default_idx = match global.defaults.language.as_deref() {
            Some("kotlin") => 1,
            _ => 0,
        };
        prompt_select("Language", &["java", "kotlin"], default_idx)?
    } else {
        global
            .defaults
            .language
            .as_deref()
            .unwrap_or("java")
            .to_string()
    };

    let loaders = if !opts.loaders.is_empty() {
        opts.loaders
    } else if interactive {
        prompt_multiselect("Loaders", &["fabric", "neoforge"])?
    } else {
        vec!["fabric".to_string(), "neoforge".to_string()]
    };

    if loaders.is_empty() {
        return Err(crate::error::McmodError::Other(
            "At least one loader must be selected".to_string(),
        ));
    }

    // Minecraft version targets
    let mc_targets: Vec<String> = if !opts.minecraft_versions.is_empty() {
        opts.minecraft_versions
    } else if interactive {
        let supported = version_meta::supported_versions();
        let selections = prompt_multiselect("Minecraft versions to target", &supported)?;
        if selections.is_empty() {
            // Default to latest
            vec![supported.last().unwrap().to_string()]
        } else {
            selections
        }
    } else {
        // Default: latest supported version
        vec![version_meta::supported_versions()
            .last()
            .unwrap()
            .to_string()]
    };

    // Validate all targets exist in version_meta
    for target in &mc_targets {
        if version_meta::get_version_meta(target).is_none() {
            return Err(crate::error::McmodError::Other(format!(
                "Unsupported Minecraft version: {target}. Supported: {}",
                version_meta::supported_versions().join(", ")
            )));
        }
    }

    let target_refs: Vec<&str> = mc_targets.iter().map(|s| s.as_str()).collect();
    let version_targets: Vec<VersionTarget> = version_meta::targets_to_ranges(&target_refs);

    let ci = if let Some(c) = opts.ci {
        c
    } else if interactive {
        prompt_confirm("Enable CI (GitHub Actions)?", true)?
    } else {
        true
    };

    let server = if let Some(s) = opts.server {
        s
    } else if interactive {
        let wants_server = prompt_confirm("Enable server-side support?", false)?;
        if wants_server {
            println!(
                "\n  {}",
                "  To run a Minecraft server, you must accept the Minecraft EULA.".white()
            );
            println!(
                "  {}",
                "  Read it here: https://aka.ms/MinecraftEULA".cyan()
            );
            let accepted = prompt_confirm("  Do you accept the Minecraft EULA?", false)?;
            if !accepted {
                println!(
                    "{}",
                    "  Server support skipped (EULA not accepted).".yellow()
                );
            }
            accepted
        } else {
            false
        }
    } else {
        false
    };

    // Publishing prompts
    let publishing_enabled = if let Some(p) = opts.publishing {
        p
    } else if interactive {
        prompt_confirm("Enable Modrinth/CurseForge publishing?", false)?
    } else {
        false
    };

    let (modrinth_id, curseforge_id) = if publishing_enabled {
        let mr_id = if let Some(id) = opts.modrinth_id {
            id
        } else if interactive {
            prompt_input("Modrinth project slug", &mod_id)?
        } else {
            mod_id.clone()
        };
        let cf_id = if let Some(id) = opts.curseforge_id {
            if id.is_empty() {
                None
            } else {
                Some(id)
            }
        } else if interactive {
            let input = prompt_input("CurseForge project ID (leave blank to skip)", "")?;
            if input.is_empty() {
                None
            } else {
                Some(input)
            }
        } else {
            None
        };
        (Some(mr_id), cf_id)
    } else {
        (None, None)
    };

    let testing = if let Some(t) = opts.testing {
        t
    } else if interactive {
        prompt_confirm("Enable testing (unit tests + GameTest)?", true)?
    } else {
        true
    };

    // Build Versions config
    let versions = Versions {
        targets: version_targets,
        architectury_plugin: version_meta::best_plugin_version(&target_refs).to_string(),
        architectury_loom: version_meta::best_loom_version(&target_refs).to_string(),
    };

    let has_fabric = loaders.iter().any(|l| l == "fabric");
    let has_neoforge = loaders.iter().any(|l| l == "neoforge");

    let publishing_config = if publishing_enabled {
        Some(crate::config::Publishing {
            modrinth_id: modrinth_id
                .as_deref()
                .unwrap_or(&mod_id)
                .to_string(),
            curseforge_id: curseforge_id.clone(),
        })
    } else {
        None
    };

    // Build McmodConfig
    let config = McmodConfig::new(
        mod_id.clone(),
        mod_name.clone(),
        package.clone(),
        author.clone(),
        description.clone(),
        language.clone(),
        has_fabric,
        has_neoforge,
        ci,
        testing,
        publishing_config,
        versions,
    );

    // Build template variables
    let vars = template::build_common_vars(&config);

    // Create project directory
    let project_dir = &opts.dir;
    crate::util::ensure_dir(project_dir)?;

    println!(
        "{}",
        format!("  Creating project in {}", project_dir.display()).cyan()
    );

    // Write Stonecutter project files
    write_stonecutter_files(project_dir, &config, &vars)?;

    // Write common source (root src/)
    write_common_source(project_dir, &vars, &language)?;

    // Write loader modules
    if has_fabric {
        write_fabric_module(project_dir, &vars, &language)?;
        println!("{}", "  Created fabric/ module".green());
    }
    if has_neoforge {
        write_neoforge_module(project_dir, &vars, &language)?;
        println!("{}", "  Created neoforge/ module".green());
    }

    // Per-version gradle.properties
    for target in &config.versions.targets {
        let ver_vars = template::build_version_vars(target);
        let content = render(template::SC_VERSION_GRADLE_PROPERTIES, &ver_vars)?;
        write_file(
            &project_dir.join(format!("versions/{}/gradle.properties", target.minecraft)),
            &content,
        )?;
        println!(
            "{}",
            format!("  Created versions/{}/gradle.properties", target.minecraft).green()
        );
    }

    // Copy global options.txt template into run/ (shared by both loaders)
    match create_run_options(project_dir, &global) {
        Ok(()) => println!("{}", "  Created run/options.txt".green()),
        Err(e) => eprintln!(
            "  {}",
            format!("Warning: Could not create options.txt: {e}").yellow()
        ),
    }

    // Write dev-defaults data pack using the active (first) version
    let active_mc = config.active_version();
    match crate::pack_format::write_dev_datapack(project_dir, &global, active_mc) {
        Ok(()) => println!(
            "{}",
            "  Created run/world/datapacks/dev-defaults/".green()
        ),
        Err(e) => eprintln!(
            "  {}",
            format!("Warning: Could not create dev data pack: {e}").yellow()
        ),
    }

    // Write server files if server support enabled
    if server {
        write_file(
            &project_dir.join("run/eula.txt"),
            "# Accepted during mcmod init\n# https://aka.ms/MinecraftEULA\neula=true\n",
        )?;
        write_file(
            &project_dir.join("run/server.properties"),
            SERVER_PROPERTIES,
        )?;
        println!("{}", "  Created run/eula.txt (EULA accepted)".green());
        println!(
            "{}",
            "  Created run/server.properties (online-mode=false)".green()
        );
    }

    // Write CI
    if ci {
        crate::commands::add::add_ci_files(project_dir, &vars)?;
        println!("{}", "  Created .github/workflows/build.yml".green());
    }

    // Write mcmod.toml
    config.save(project_dir)?;

    // Print success
    let target_list = config
        .versions
        .targets
        .iter()
        .map(|t| {
            if t.minecraft == t.max_minecraft {
                t.minecraft.clone()
            } else {
                format!("{}-{}", t.minecraft, t.max_minecraft)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");

    println!("\n{}", "  Project created successfully!".bold().green());
    println!();
    println!("  {}", format!("  Mod ID:      {mod_id}").white());
    println!("  {}", format!("  Mod Name:    {mod_name}").white());
    println!("  {}", format!("  Package:     {package}").white());
    println!("  {}", format!("  Language:    {language}").white());
    println!(
        "  {}",
        format!("  Loaders:     {}", loaders.join(", ")).white()
    );
    println!(
        "  {}",
        format!("  MC Targets:  {target_list}").white()
    );
    println!("  {}", format!("  CI:          {ci}").white());
    println!("  {}", format!("  Testing:     {testing}").white());
    println!();
    println!("  {}", "  Next steps:".bold());
    println!("    cd {}", project_dir.display());
    println!("    ./gradlew chiseledBuild");
    println!();

    Ok(())
}

// --- File writing ---

fn write_stonecutter_files(
    dir: &Path,
    config: &McmodConfig,
    vars: &HashMap<String, String>,
) -> Result<()> {
    let has_fabric = config.loaders.fabric;
    let has_neoforge = config.loaders.neoforge;
    let is_kotlin = config.mod_info.language == "kotlin";

    let conditions = &[
        ("fabric", has_fabric),
        ("neoforge", has_neoforge),
        ("kotlin", is_kotlin),
    ];

    // stonecutter.gradle.kts
    write_file(
        &dir.join("stonecutter.gradle.kts"),
        &render(template::SC_STONECUTTER_GRADLE, vars)?,
    )?;

    // settings.gradle.kts — strip conditional blocks first, then render
    let settings = strip_conditional_blocks(template::SC_SETTINGS_GRADLE, conditions);
    write_file(&dir.join("settings.gradle.kts"), &render(&settings, vars)?)?;

    // build.gradle.kts — strip conditionals first (removes {{kotlin_version}} if not kotlin), then render
    let build = strip_conditional_blocks(template::SC_BUILD_GRADLE, conditions);
    write_file(&dir.join("build.gradle.kts"), &render(&build, vars)?)?;

    // gradle.properties — shared props
    write_file(
        &dir.join("gradle.properties"),
        &render(template::SC_GRADLE_PROPERTIES, vars)?,
    )?;

    // .gitignore
    write_file(&dir.join(".gitignore"), template::TMPL_GITIGNORE)?;

    // LICENSE
    write_file(&dir.join("LICENSE"), &render(template::TMPL_LICENSE, vars)?)?;

    // Gradle wrapper
    write_binary(
        &dir.join("gradle/wrapper/gradle-wrapper.jar"),
        template::GRADLE_WRAPPER_JAR,
    )?;
    write_file(
        &dir.join("gradle/wrapper/gradle-wrapper.properties"),
        template::GRADLE_WRAPPER_PROPS,
    )?;
    write_binary(&dir.join("gradlew"), template::GRADLEW)?;
    write_binary(&dir.join("gradlew.bat"), template::GRADLEW_BAT)?;

    // Set gradlew as executable (Unix)
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(dir.join("gradlew"))?.permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(dir.join("gradlew"), perms)?;
    }

    println!("{}", "  Created Stonecutter project files".green());
    Ok(())
}

/// Write shared source files into root `src/` (the Stonecutter "common" project).
fn write_common_source(
    dir: &Path,
    vars: &HashMap<String, String>,
    language: &str,
) -> Result<()> {
    let package_path = vars.get("package_path").unwrap();
    let class_name = vars.get("class_name").unwrap();
    let mod_id = vars.get("mod_id").unwrap();

    let (template, ext, source_dir) = if language == "kotlin" {
        (template::TMPL_COMMON_MOD_KT, "kt", "kotlin")
    } else {
        (template::TMPL_COMMON_MOD_JAVA, "java", "java")
    };

    let source_path = dir.join(format!(
        "src/main/{source_dir}/{package_path}/{class_name}.{ext}"
    ));
    write_file(&source_path, &render(template, vars)?)?;

    // assets/<mod_id>/icon.png.txt
    write_file(
        &dir.join(format!(
            "src/main/resources/assets/{mod_id}/icon.png.txt"
        )),
        "Replace this file with your mod icon (icon.png)\n",
    )?;

    println!("{}", "  Created common source in src/".green());
    Ok(())
}

fn write_fabric_module(
    dir: &Path,
    vars: &HashMap<String, String>,
    language: &str,
) -> Result<()> {
    let package_path = vars.get("package_path").unwrap();
    let class_name = vars.get("class_name").unwrap();
    let mod_id = vars.get("mod_id").unwrap();

    // fabric/build.gradle.kts
    write_file(
        &dir.join("fabric/build.gradle.kts"),
        template::SC_FABRIC_BUILD_GRADLE,
    )?;

    // fabric/gradle.properties (just loom.platform)
    write_file(
        &dir.join("fabric/gradle.properties"),
        template::TMPL_FABRIC_GRADLE_PROPS,
    )?;

    // fabric.mod.json — has both {{}} CLI placeholders and ${} Gradle expand tokens
    write_file(
        &dir.join("fabric/src/main/resources/fabric.mod.json"),
        &render(template::SC_FABRIC_MOD_JSON, vars)?,
    )?;

    // Mixins JSON
    write_file(
        &dir.join(format!("fabric/src/main/resources/{mod_id}.mixins.json")),
        &render(template::TMPL_FABRIC_MIXINS_JSON, vars)?,
    )?;

    // Mixin package-info.java
    write_file(
        &dir.join(format!(
            "fabric/src/main/java/{package_path}/mixin/package-info.java"
        )),
        &render(template::TMPL_FABRIC_MIXIN_PACKAGE_INFO, vars)?,
    )?;

    // Entry point source file
    let (tmpl, ext, src_dir) = if language == "kotlin" {
        (template::TMPL_FABRIC_MOD_KT, "kt", "kotlin")
    } else {
        (template::TMPL_FABRIC_MOD_JAVA, "java", "java")
    };

    write_file(
        &dir.join(format!(
            "fabric/src/main/{src_dir}/{package_path}/fabric/{class_name}Fabric.{ext}"
        )),
        &render(tmpl, vars)?,
    )?;

    Ok(())
}

fn write_neoforge_module(
    dir: &Path,
    vars: &HashMap<String, String>,
    language: &str,
) -> Result<()> {
    let package_path = vars.get("package_path").unwrap();
    let class_name = vars.get("class_name").unwrap();

    // neoforge/build.gradle.kts
    write_file(
        &dir.join("neoforge/build.gradle.kts"),
        template::SC_NEOFORGE_BUILD_GRADLE,
    )?;

    // neoforge/gradle.properties (just loom.platform)
    write_file(
        &dir.join("neoforge/gradle.properties"),
        template::TMPL_NEOFORGE_GRADLE_PROPS,
    )?;

    // neoforge.mods.toml — has both {{}} CLI placeholders and ${} Gradle expand tokens
    write_file(
        &dir.join("neoforge/src/main/resources/META-INF/neoforge.mods.toml"),
        &render(template::SC_NEOFORGE_MODS_TOML, vars)?,
    )?;

    // Entry point source file
    let (tmpl, ext, src_dir) = if language == "kotlin" {
        (template::TMPL_NEOFORGE_MOD_KT, "kt", "kotlin")
    } else {
        (template::TMPL_NEOFORGE_MOD_JAVA, "java", "java")
    };

    write_file(
        &dir.join(format!(
            "neoforge/src/main/{src_dir}/{package_path}/neoforge/{class_name}NeoForge.{ext}"
        )),
        &render(tmpl, vars)?,
    )?;

    Ok(())
}

// --- Prompt helpers ---

fn prompt_input(prompt: &str, default: &str) -> Result<String> {
    let result = dialoguer::Input::<String>::new()
        .with_prompt(format!("  {prompt}"))
        .default(default.to_string())
        .interact_text()
        .map_err(|e| crate::error::McmodError::Other(e.to_string()))?;
    Ok(result)
}

fn prompt_select(prompt: &str, items: &[&str], default: usize) -> Result<String> {
    let selection = dialoguer::Select::new()
        .with_prompt(format!("  {prompt}"))
        .items(items)
        .default(default)
        .interact()
        .map_err(|e| crate::error::McmodError::Other(e.to_string()))?;
    Ok(items[selection].to_string())
}

fn prompt_multiselect(prompt: &str, items: &[&str]) -> Result<Vec<String>> {
    let defaults = vec![true; items.len()];
    let selections = dialoguer::MultiSelect::new()
        .with_prompt(format!("  {prompt}"))
        .items(items)
        .defaults(&defaults)
        .interact()
        .map_err(|e| crate::error::McmodError::Other(e.to_string()))?;
    Ok(selections.iter().map(|&i| items[i].to_string()).collect())
}

fn prompt_confirm(prompt: &str, default: bool) -> Result<bool> {
    let result = dialoguer::Confirm::new()
        .with_prompt(format!("  {prompt}"))
        .default(default)
        .interact()
        .map_err(|e| crate::error::McmodError::Other(e.to_string()))?;
    Ok(result)
}

fn create_run_options(
    project_dir: &Path,
    config: &crate::global_config::GlobalConfig,
) -> Result<()> {
    let run_dir = project_dir.join("run");
    crate::util::ensure_dir(&run_dir)?;
    crate::global_config::copy_options_to(&run_dir.join("options.txt"), config)
}

/// Converts an author name to a valid Java package segment (lowercase, alphanumeric).
fn slugify_for_package(author: &str) -> String {
    let slug: String = author
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .map(|c| c.to_ascii_lowercase())
        .collect();

    if slug.is_empty() || slug.starts_with(|c: char| c.is_ascii_digit()) {
        "example".to_string()
    } else {
        slug
    }
}

/// Converts a directory name to a valid mod ID (lowercase, underscores).
fn slugify_dir_name(dir: &Path) -> String {
    let name = dir
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("mymod");

    let slug: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect();

    let slug: String = slug
        .split('_')
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("_");

    if slug.is_empty() || slug.starts_with(|c: char| c.is_ascii_digit()) {
        "mymod".to_string()
    } else {
        slug
    }
}

fn default_mod_name(mod_id: &str) -> String {
    mod_id
        .split('_')
        .filter(|s| !s.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => {
                    let mut s = c.to_uppercase().to_string();
                    s.extend(chars);
                    s
                }
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}
